### ISSUE TITLE
[1.12.2] Crafting crash with recipe from Basketcase

### ISSUE THREAD

**Issue by DWX12** [CreativeMD/InGameConfigManager#53] opened 2019-04-30 08:07 UTC
Received a crash when attempting to use a recipe from the Basketcase mod. The recipe takes any vanilla log and an axe (used a diamond axe) and upon putting the axe in the crafting grid to the center right of oak log, the game crashed.

https://paste.dimdev.org/uwahuxucan.mccrash

**Comment by CreativeMD** [comment] 2019-04-30 09:01
This crash is not caused by IGCM but by another mod. I don't know which one, but it appears to be a mod which tries to enhance the game's performance. I would recommend to remove some of these mods and see if it still crashes, till you find the mod which causes the issue.

**Comment by CreativeMD** [comment] 2019-05-01 08:59
I will close this issue for now. If it is caused by IGCM just reopen it.

**Closed as completed by CreativeMD** 2019-05-01 08:59 UTC

**Comment by DWX12** [comment] 2019-06-02 21:08
No problem. If anything more comes of this then I will post it. Thanks for the reply though.
